apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantogen-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plantogen
  template:
    metadata:
      labels:
        app: plantogen
    spec:
      containers:
      - name: plantogen
        image: plantogen:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: plantogen-service
spec:
  selector:
    app: plantogen
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
